/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.perpustakaan.ui.transaksi.pengembalian;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.perpustakaan.Main;
import org.perpustakaan.model.Pengembalian;

/**
 *
 * @author ngarambes
 */
public class FormPengembalian extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPengembalian
     */
    private DefaultTableModel tabmode;
    
    void showPengembalian(){
        Object[] column = {"Id Pengembalian", "Id Peminjaman", "Peminjam", "Tanggal Pinjam", "Tanggal Kembali"};
        Object[][] data = new Object[Main.getPengembalianService().getPengembalians().size()][5];
        int i = 0;
        for (Pengembalian p: Main.getPengembalianService().getPengembalians()){
            Object[] arr_data = {p.getId(), p.getPeminjaman().getId(), p.getPeminjaman().getAnggota().getNama()
                    , p.getPeminjaman().getTanggal(), p.getTanggal()};
            data[i] = arr_data;
            i++;
        }
        tabmode = new DefaultTableModel(data, column);
        tabelPengembalian.setModel(tabmode);
    }
    
    public FormPengembalian() {
        initComponents();
        showPengembalian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengembalian = new javax.swing.JTable();
        bTandai = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        jLabel1.setText("PENGEMBALIAN");

        tabelPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tabelPengembalian);

        bTandai.setText("Tandai Kembalikan Buku");
        bTandai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTandaiActionPerformed(evt);
            }
        });

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bTandai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bKeluar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTandai)
                    .addComponent(bKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bTandaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTandaiActionPerformed
        int tabel = tabelPengembalian.getSelectedRow();
        if(tabel == -1){
            JOptionPane.showMessageDialog(null, "pilih salah salah satu riwayat");
            return;
        }
        String nama = tabelPengembalian.getValueAt(tabel, 2).toString();
        int confirm = JOptionPane.showConfirmDialog(null, "Tandai "+nama+" telah mengembalikan buku? \n"
                + "Catatan: Riwayat yang telah ditandai tidak dapat dikembalikan", "Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
        if(confirm == JOptionPane.OK_OPTION){
            Long id = Long.parseLong(tabelPengembalian.getValueAt(tabel, 0).toString());
            Main.pengembalian = Main.getPengembalianService().getPengembalian(id);
            Main.pengembalian.setTanggal(new Date());
            Main.getPengembalianService().save(Main.pengembalian);
            showPengembalian();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bTandaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bTandai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPengembalian;
    // End of variables declaration//GEN-END:variables
}
