/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.perpustakaan.ui.buku;

import org.perpustakaan.ui.anggota.FormAnggotaUbah;
import org.perpustakaan.ui.anggota.FormAnggotaTambah;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.perpustakaan.Main;
import org.perpustakaan.model.Anggota;
import org.perpustakaan.model.Buku;

/**
 *
 * @author ngarambes
 */
public class FormBuku extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAnggota
     */
    private DefaultTableModel tabmode;
    void showByJudul(String judul){
        Object[] column = {"Id Buku", "Judul Buku", "Pengarang", "Penerbit"};
        Object[][] data = new Object[Main.getBukuService().getByJudul(judul).size()][4];
        int i = 0;
        for(Buku b:Main.getBukuService().getByJudul(judul)){
            Object [] arr_data = {b.getId(), b.getJudul(), b.getPengarang(), b.getPenerbit()};
            data[i] = arr_data;
            i++;
        }
        tabmode = new DefaultTableModel(data, column);
        tabelBuku.setModel(tabmode);
    }
    void showBuku(){
        Object[] column = {"Id Buku", "Judul Buku", "Pengarang", "Penerbit"};
        Object[][] data = new Object[Main.getBukuService().getBukus().size()][4];
        int i= 0;
        
        for(Buku b: Main.getBukuService().getBukus()){
            Object[] arr_data = {b.getId(), b.getJudul(), b.getPengarang(), b.getPenerbit()};
            data[i] = arr_data;
            i++;
        }
        tabmode = new DefaultTableModel(data, column);
        tabelBuku.setModel(tabmode);
    }
    public FormBuku() {
        initComponents();
        showBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bKeluar = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBuku);

        jLabel1.setText("DAFTAR BUKU");

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        bRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh kecil.png"))); // NOI18N
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Buku Berdasarkan Judul");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(bKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKeluar)
                    .addComponent(bTambah)
                    .addComponent(bUbah)
                    .addComponent(bHapus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        showBuku();
        // TODO add your handling code here:
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int tabel = tabelBuku.getSelectedRow();
        Long id = 0l;
        String judul ="", pengarang = "", penerbit="";
        if(tabel == -1){
            JOptionPane.showMessageDialog(null, "Buku belum dipilh");
            return;
        }
        try{
            id = Long.parseLong(tabelBuku.getValueAt(tabel, 0).toString());
            judul = tabelBuku.getValueAt(tabel, 1).toString();
            pengarang = tabelBuku.getValueAt(tabel, 2).toString();
            penerbit = tabelBuku.getValueAt(tabel, 3).toString();
        } catch(Exception e){
            e.printStackTrace();
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, "Hapus Buku "+judul+"?", "Konfimasi", JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.OK_OPTION){
            Main.buku = new Buku();
            Main.buku.setId(id);
            Main.buku.setJudul(judul);
            Main.buku.setPengarang(pengarang);
            Main.buku.setPenerbit(penerbit);
            Main.getBukuService().delete(Main.buku);
            showBuku();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        Main.buku = new Buku();
        FormBukuTambah fbt = new FormBukuTambah();        
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(fbt);
        fbt.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        showBuku();
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        
        int tabel = tabelBuku.getSelectedRow();
        if(tabel== -1){
            JOptionPane.showMessageDialog(null, "Buku belum dipilih");
            return;
        }
        Main.buku = new Buku();
        Long id = 0l;
        String judul="", pengarang = "", penerbit= "";
        
        id = Long.parseLong(tabelBuku.getValueAt(tabel, 0).toString());
        judul = tabelBuku.getValueAt(tabel, 1).toString();
        pengarang = tabelBuku.getValueAt(tabel, 2).toString();
        penerbit = tabelBuku.getValueAt(tabel, 3).toString();
        
        FormBukuUbah fbu = new FormBukuUbah(id,judul,pengarang,penerbit);
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(fbu);
        fbu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bUbahActionPerformed
    
    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        String judul;
        try {
            judul = tfCari.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Harap masukkan data pencarian yang benar");
            return;
        }
        showByJudul(judul);
                
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBuku;
    private javax.swing.JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}
