/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.perpustakaan.ui.transaksi.peminjaman;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.perpustakaan.Main;
import org.perpustakaan.model.Buku;
import org.perpustakaan.model.PeminjamanDetail;
import org.perpustakaan.model.Pengembalian;

/**
 *
 * @author ngarambes
 */
public class FormPeminjaman extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPeminjaman
     */
    private DefaultTableModel tabmode;
    
    void showPeminjamanDetails(){
        Object[] column = {"Id Buku", "Judul Buku", "Pengarang"};
        Object [][] data = new Object[Main.peminjaman.getPeminjamanDetails().size()][3];
        int i = 0;
        for(PeminjamanDetail pd: Main.peminjaman.getPeminjamanDetails()){
            Object[] arr_data = {pd.getBuku().getId(), pd.getBuku().getJudul(), pd.getBuku().getPengarang()};
            data[i] = arr_data;
            i++;
        }
        tabmode = new DefaultTableModel(data, column);
        tabelPeminjamanDetail.setModel(tabmode);
    }
    public FormPeminjaman(String nama){
        initComponents();
        lblPeminjam.setText(nama);
        showPeminjamanDetails();
    }
    public FormPeminjaman() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjamanDetail = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblPeminjam = new javax.swing.JLabel();
        bRefresh = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();

        jLabel1.setText("PEMINJAMAN BARU");

        tabelPeminjamanDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabelPeminjamanDetail);

        jLabel2.setText("Peminjam :");

        lblPeminjam.setText("null");

        bRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh kecil.png"))); // NOI18N
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPeminjam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblPeminjam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bHapus)
                    .addComponent(bKeluar)
                    .addComponent(bSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Keluar dari transaksi?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(confirm == JOptionPane.OK_OPTION)
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        FormPeminjaman_PilihBuku pb = new FormPeminjaman_PilihBuku();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(pb);
        pb.setVisible(true);
        this.setEnabled(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        showPeminjamanDetails();
        // TODO add your handling code here:
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int tabel = tabelPeminjamanDetail.getSelectedRow();
        if (tabel == -1 ){
            JOptionPane.showMessageDialog(null, "Pilih salah satu buku");
            return;
        }
        
        List<PeminjamanDetail> toRemove = new ArrayList<>();
               
        for(PeminjamanDetail pd : Main.peminjaman.getPeminjamanDetails()){
            if(pd.getBuku().getId() == tabelPeminjamanDetail.getValueAt(tabel, 0)){
                toRemove.add(pd);
                
            }
        }
        Main.peminjaman.getPeminjamanDetails().removeAll(toRemove);
        showPeminjamanDetails();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Simpan transaksi?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(confirm == JOptionPane.OK_OPTION){
           
            
            Main.getpemiPeminjamanService().save(Main.peminjaman);
                       
            FormPeminjaman_Riwayat fpr = new FormPeminjaman_Riwayat();
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(fpr);
            fpr.setVisible(true);
            this.dispose();
        }
                
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPeminjam;
    private javax.swing.JTable tabelPeminjamanDetail;
    // End of variables declaration//GEN-END:variables
}
